steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      java-version: '14'
      distribution: 'adopt'
  - run: mvn --batch-mode --update-snapshots clean package
  - run: mkdir staging && cp target/*.zip staging
  - uses: actions/upload-artifact@v3
    with:
      name: Package
      path: staging